version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: taskdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: taskapp
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: qwerty
      DB_NAME: taskdb
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: